services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    # environment:
    #   - "DJANGO_SECRET_KEY=django-insecure--5dnh&3y+j-=4t-3lxq*#302m9l2xys80fy89_jn0woes4ce^k"
    #   - 'DEBUG=True'
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=postgres"
 