# Generated by Django 6.0.5 on 2026-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('ua', 'unavailable'), ('a', 'available')], default='w', max_length=2),
        ),
    ]
