# Generated by Django 6.0.5 on 2026-05-14 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.categories'),
        ),
    ]
