# Generated by Django 6.1 on 2026-08-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_remove_product_categories_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='product.category')),
            ],
        ),
    ]
