# Generated by Django 6.1 on 2026-08-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_category_product_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product'),
        ),
    ]
