# Generated by Django 6.1 on 2026-08-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='items',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='product.product'),
        ),
    ]
