# Generated by Django 6.1 on 2026-08-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
    ]
